"""We add descriptions to models

Revision ID: d688dd5f3d4f
Revises: 44888c872739
Create Date: 2023-09-26 16:09:37.196942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd688dd5f3d4f'
down_revision = '44888c872739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=600), nullable=True))

    with op.batch_alter_table('user_planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=600), nullable=True))

    with op.batch_alter_table('user_starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=600), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_starship', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('user_planet', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('user_character', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
